<?php
include('job_card_pagination_pending.php'); 
if ($sess_allow_view==0)
{
include ('includes/restricted.php');
}
else
{
 ?><?php
if(isset($_GET['subDELETEsettlement']))
  { 
$settlement_id=$_GET['settlement_id'];
 delete_settlement($settlement_id);
  }
  
 $location_id=$_POST['location_id'];
$settlement_name=$_POST['settlement_name'];
?>

<script type="text/javascript"> 

function confirmDelete()
{
    return confirm("Are you sure you want to cancel");
}

</script>

<?php include ('includes/facebox.php'); ?>
<form name="search" method="post" action=""> 
<table width="100%" border="0">
  <tr bgcolor="#FFFFCC">
   
    <td colspan="11" height="30" align="center"> 
	<?php

if ($_GET['updateuserconfirm']==1)
echo '<div align="center" style="background: #FFCC33; height:20px; width:550px; border:#FF0000 solid 1px; font-size:11px;" class="br-5"> <p align="center"><font color="#FF0000" >User Updated Successfully!!</font></strong></p></div>';
?> 

<?php 

if ($_GET['deleteconfirm']==1)
echo '<div align="center" style="background: #FFCC33; height:20px; width:550px; border:#FF0000 solid 1px; font-size:11px;" class="br-5"> <p align="center"><font color="#FF0000" >Record Deleted Successfully!!</font></strong></p></div>';
?>
	
	</td>
	
    </tr>
	<tr height="30" bgcolor="#FFFFCC">
   

    <td width="23%" colspan="11" align="center">   <strong>Filter By Customer<font color="#FF0000">* </font></strong>
	<select name="location_id"><option value="0">Select..........................................................</option>
								  <?php
								  
								  $query1="select * from customer order by customer_name asc";
								  $results1=mysql_query($query1) or die ("Error: $query1.".mysql_error());
								  
								  if (mysql_num_rows($results1)>0)
								  
								  {
									  while ($rows1=mysql_fetch_object($results1))
									  
									  { ?>
										  
                                    <option value="<?php echo $rows1->customer_id;?>"><?php echo $rows1->customer_name; ?> </option>
                                    
                                
										  
										<?php  }
									  
									  
									  }
									  
									  
								  
								  
								  
								  
								  
								  ?></select>
								  
								  
								  <strong>Or By Job Card No<font color="#FF0000">* </font>
								  
				 <input type="text" name="settlement_name" size="40" />				  
								  
<input type="submit" name="generate" value="Generate">		

<a target="_blank" style="float:right; margin-right:200px; font-weight:bold; font-size:13px; color:#000000" href="print_list_job_cards_canceled.php?customer_id=<?php echo $location_id?>">Print</a>						  
<a  style="float:right; margin-right:100px; font-weight:bold; font-size:13px; color:#000000" href="print_list_job_cards_canceled_excel.php?customer_id=<?php echo $location_id ?>">Export To Excel</a>						  
						  
								  
								  </td>
    
  </tr>
  
  <tr bgcolor="#FFFFCC" height="30">
	<td colspan="13" ><?//=$pagination?>
	
	</td></tr>
  
  <tr  style="background:url(images/description.gif);" height="30" >
  
    <!--<td align="center" width="150"><strong>Job Card No</strong></td>-->
    <td align="center" width="150"><strong>Job Card No</strong></td>
    <td align="center" width="150"><strong>Date Generated</strong></td>
	 <td align="center" width="300"><strong>Customer Name</strong></td> 
	<td align="center" width="100"><strong>Start Date</strong></td>
	<td align="center" width="100"><strong>Completion Date</strong></td>
    <td align="center" width="160"><strong>Period</strong></td>  	
    <td align="center" width="150"><strong>Technician</strong></td>
    <td align="center" width="150"><strong>Generated By</strong></td>    
    <td align="center" width="150"><strong>View Details</strong></td>    
  <!--  <td align="center" width="150"><strong>Job Card Details</strong></td> -->
	
	<td align="center" width="100"><strong>Cancel</strong></td>
    </tr>


 <?php 
if (!isset($_POST['generate']))
{ 

 
$sql="SELECT * FROM job_cards where canceled_status='1' and approved_status='0' order by date_generated desc";
$results= mysql_query($sql) or die ("Error $sql.".mysql_error());
}
else
{
$location_id=$_POST['location_id'];
$settlement_name=$_POST['settlement_name'];
if ($location_id!=0 && $settlement_name=='')
{
$sql="SELECT * FROM job_cards where customer_id='$location_id' and canceled_status='1' and approved_status='0' order by date_generated desc";
$results= mysql_query($sql) or die ("Error $sql.".mysql_error());

}

elseif ($location_id==0 && $settlement_name!='')
{
$sql="SELECT * FROM job_cards where job_card_id LIKE '%$settlement_name%' and canceled_status='1' and approved_status='0' order by date_generated desc";
$results= mysql_query($sql) or die ("Error $sql.".mysql_error());
}

elseif ($location_id!=0 && $settlement_name!='')
{
$sql="SELECT * FROM job_cards WHERE customer_id='$location_id' and canceled_status='1' and approved_status='0' AND job_card_id LIKE 
'%$settlement_name%' order by date_generated desc";
$results= mysql_query($sql) or die ("Error $sql.".mysql_error());
}
else
{
$sql="SELECT * FROM job_cards where canceled_status='1' and approved_status='0' order by date_generated desc LIMIT $start, $limit";
$results= mysql_query($sql) or die ("Error $sql.".mysql_error());

}

}
if (mysql_num_rows($results) > 0)
						  {
							  $RowCounter=0;
							  while ($rows=mysql_fetch_object($results))
							  { 
							  
							  $RowCounter++;
							  if($RowCounter % 2==0)
{
echo '<tr bgcolor="#C0D7E5" height="25">';
}
else 
{
echo '<tr bgcolor="#FFFFCC" height="25" >';
}
 
 
 ?>
  
   
    <!--<td><?php echo $job_card_id=$rows->job_card_id;?></td>-->
    <td><?php echo $job_card_id=$rows->job_card_id;?></td>
    <td><?php echo $rows->start_date;?></td>
    <td>
	<?php 
	 $customer_id=$rows->customer_id;
	
$sqllpdet="SELECT * from customer where customer_id='$customer_id'";
$resultslpdet= mysql_query($sqllpdet) or die ("Error $sqllpdet.".mysql_error());
$rowslpdet=mysql_fetch_object($resultslpdet);
	
	
	echo $rowslpdet->customer_name;?>
	
	
	</td>
    <td align="center"><?php echo $reg_no=$rows->start_date;?></td>
    <td align="center">
	
	<?php echo $rows->end_date;?>
	
	
	</td>
    
	<td align="center">
	
	<?php
/* $sqlpt="SELECT * from released_item where job_card_id='$job_card_id'";
$resultspt= mysql_query($sqlpt) or die ("Error $sqlpt.".mysql_error());
echo $rowspt=mysql_num_rows($resultspt); */

//echo $rows->end_date;

$begin_date=$rows->start_date;
$end_date=$rows->end_date;

$today=date('Y-m-d');
$now = strtotime("$end_date"); // or your date as well
     $your_date = strtotime("$today");
     $datediff = $now - $your_date;
	 
	 $datediff2 = $your_date-$now;
     $due_days=floor($datediff/(60*60*24));
	 $over_due_days=floor($datediff2/(60*60*24));
 
	 
	 if ($due_days <0)
	 {
	  echo "<font color='#ff0000'>Over Due By ".$over_due_days. " Days</font>";
	 }
	 else
	 {
	 echo "<font color='#109100'>".$due_days." Days</font>"; 
	 }

	?>
	
	
	
	</td>
	

	
	
	
	<td>
	         <?php 
$techniacian_id=$rows->technician_id;
$sqluser="select * FROM users WHERE user_id='$techniacian_id'";
$resultsuser= mysql_query($sqluser) or die ("Error $sqluser.".mysql_error());
	
$rowsuser=mysql_fetch_object($resultsuser);	

echo $rowsuser->f_name;
	
	
	
	?>
	
	</strong></td>
	<td>
	<i><font size="-2">
	<?php $staff=$rows->user_id;
$sqlst="SELECT * FROM  users where user_id='$staff'";
$resultst= mysql_query($sqlst) or die ("Error $sqlst.".mysql_error());	
$rowst=mysql_fetch_object($resultst);	
echo $rowst->f_name;
	?>
	
	</font></i>
	
	</td>
  <td align="right"><a href="home.php?viewcountries=viewcountries&job_card_id=<?php echo $rows->job_card_id; ?>">View Job Card Details</a></td>

<td align="center"><a rel="facebox" onClick="return confirmDelete();" href="cancel_submited_invoices.php?job_card_id=<?php echo $rows->job_card_id; ?>">Cancel</a></td>
	
   
    </tr>

  <?php 
  
  }
  
  }
  
  else 
  
  {
  ?>
  
  <tr bgcolor="#FFFFCC" height="30"><td colspan="11" align="center"><font color="#ff0000"><strong>No Results found!!</strong></font></td></tr>
  
  <?php 
  
  
  }
  
  
  ?>
  
  </table>
   </td></tr>	 
  
  
  
  
  
  
</table>
</form>
 <?php }?>