<?php
if ($sess_allow_add==0)
{
include ('includes/restricted.php');
}
else
{
 ?>
<?php
if(isset($_GET['subDELETEsettlement']))
  { 
$settlement_id=$_GET['settlement_id'];
 delete_settlement($settlement_id);
  }
  
  
  

  
?>

<script type="text/javascript"> 

function confirmDelete()
{
    return confirm("Are you sure you want to cancel this approved invoice?");
}

</script>
<link href="src/facebox.css" media="screen" rel="stylesheet" type="text/css" />
<script src="lib/jquery.js" type="text/javascript"></script>
<script src="src/facebox.js" type="text/javascript"></script>
  <script type="text/javascript">
	jQuery(document).ready(function($) {
	  $('a[rel*=facebox]').facebox({
		loadingImage : 'src/loading.gif',
		closeImage   : 'src/closelabel.png'
	  })
	})
  </script>
<script type="text/javascript" src="calender/calendar.js"></script>
<script type="text/javascript" src="calender/lang/calendar-en.js"></script>
<script type="text/javascript" src="calender/calendar-setup.js"></script>
<style type="text/css">

@import url(calender/calendar-win2k-1.css);

</style>

<form name="search" method="post" action=""> 
<table width="100%" border="0">
  <tr bgcolor="#FFFFCC">
   
    <td colspan="11" height="30" align="center"> 
	<?php

if ($_GET['updateuserconfirm']==1)
echo '<div align="center" style="background: #FFCC33; height:20px; width:550px; border:#FF0000 solid 1px; font-size:11px;" class="br-5"> <p align="center"><font color="#FF0000" >User Updated Successfully!!</font></strong></p></div>';
?> 

<?php 

if ($_GET['deleteconfirm']==1)
echo '<div align="center" style="background: #FFCC33; height:20px; width:550px; border:#FF0000 solid 1px; font-size:11px;" class="br-5"> <p align="center"><font color="#FF0000" >Record Deleted Successfully!!</font></strong></p></div>';
?>
	
	</td>
	
    </tr>
	<tr height="30" bgcolor="#FFFFCC">
   

    <td width="23%" colspan="11" align="center">   
<strong>Filter By Customer<font color="#FF0000">* </font></strong>
	<select name="location_id"><option value="0">Select..........................................................</option>
								  <?php
								  
								  $query1="select * from customer order by customer_name asc";
								  $results1=mysql_query($query1) or die ("Error: $query1.".mysql_error());
								  
								  if (mysql_num_rows($results1)>0)
								  
								  {
									  while ($rows1=mysql_fetch_object($results1))
									  
									  { ?>
										  
                                    <option value="<?php echo $rows1->customer_id;?>"><?php echo $rows1->customer_name; ?> </option>
                                    
                                
										  
										<?php  }
									  
									  
									  }
									  
									  
								  
								  
								  
								  
								  
								  ?></select>
								  
	<strong>Or By Date</strong>
						<strong>From : </strong><input type="text" name="from" size="30" id="from" readonly="readonly" /><strong>To:</strong>
		<input type="text" name="to" size="25" id="to" readonly="readonly" />							  
								  		  
								  
<input type="submit" name="generate" value="Generate">	
								  
								  </td>
    
  </tr>
  
  <tr  style="background:url(images/description.gif);" height="30" >
  
   <td align="center" width="150"><strong>Job Card No</strong></td>   
    <td align="center" width="150"><strong>Date Generated</strong></td>
<td align="center" width="300"><strong>Customer Name</strong></td>  
<td align="center" width="150"><strong>Invoice Value (SSP)</strong></td> 
    <td align="center" width="150"><strong>Amount Paid (SSP)</strong></td>
	 <td align="center" width="150"><strong>Balance(SSP)</strong></td> 
	<!--<td align="center" width="150"><strong>Amount(Kshs)</strong></td>-->
	<td align="center" width="150"><strong>Balance Payment Date</strong></td>    
	 <td align="center" width="150"><strong>Balance Payment Alert</strong></td>
	<td align="center" width="150"><strong>Generated By</strong></td>    
    <td align="center" width="150"><strong>View Details</strong></td>
<td align="center" width="150"><strong>Cancel Invoice</strong></td> 
    </tr>


 <?php 
 
$job_card_ttl=0;
 $inv_ttl=0;
  if (!isset($_POST['generate']))
{ 

 
$sql="SELECT * FROM job_cards where sale_type='cr' and approved_status='1' order by date_generated desc";
$results= mysql_query($sql) or die ("Error $sql.".mysql_error());
}
else
{
$location_id=$_POST['location_id'];
$settlement_name=$_POST['settlement_name'];
if ($location_id!=0 && $settlement_name=='')
{
$sql="SELECT * FROM job_cards where customer_id='$location_id' and sale_type='cr' and approved_status='1' order by date_generated desc";
$results= mysql_query($sql) or die ("Error $sql.".mysql_error());

}

elseif ($location_id==0 && $settlement_name!='')
{
$sql="SELECT * FROM job_cards where job_card_id LIKE '%$settlement_name%' and sale_type='cr' and approved_status='1'  order by date_generated desc";
$results= mysql_query($sql) or die ("Error $sql.".mysql_error());
}

elseif ($location_id!=0 && $settlement_name!='')
{
$sql="SELECT * FROM job_cards WHERE customer_id='$location_id' and sale_type='cr' and approved_status='1'  AND job_card_id LIKE 
'%$settlement_name%' order by date_generated desc";
$results= mysql_query($sql) or die ("Error $sql.".mysql_error());
}
else
{
$sql="SELECT * FROM job_cards where sale_type='cr' and approved_status='1'  order by date_generated desc";
$results= mysql_query($sql) or die ("Error $sql.".mysql_error());

}

}
if (mysql_num_rows($results) > 0)
						  {
							  $RowCounter=0;
							  while ($rows=mysql_fetch_object($results))
							  { 
							  
							  $RowCounter++;
							  if($RowCounter % 2==0)
{
echo '<tr bgcolor="#C0D7E5" height="25">';
}
else 
{
echo '<tr bgcolor="#FFFFCC" height="25" >';
}
 
 
 ?>
  
   
   <td><?php echo $job_card_id=$rows->job_card_id;?></td>
  
    <td><?php echo $rows->date_generated;?></td>
    <td>
	<?php 
	 $customer_id=$rows->customer_id;
	
$sqllpdet="SELECT * from customer where customer_id='$customer_id'";
$resultslpdet= mysql_query($sqllpdet) or die ("Error $sqllpdet.".mysql_error());
$rowslpdet=mysql_fetch_object($resultslpdet);
	
	
	echo $rowslpdet->customer_name;?>
	
	
	</td>
    <td align="right"><?php include ('invoice_value.php');?></td>
    <td align="right">
	
	<?php include ('invoice_payment_value.php');?>
	
	
	</td>
   
	<td align="right">
	
	<?php
echo number_format($bal=$task_totals-$invoice_value,2);
	?>
	
	
	
	</td>
	

	
	
	
	<td align="center">
	<?php 
	
	echo $rows->bal_date;

	
	
	?></td>
	  <td><?php 
	  
	  
	  
	  //$invoice_id=$rows->job_card_id;
	  
$begin_date=$rows->start_date;
$end_date=$rows->bal_date;

$today=date('Y-m-d');
$now = strtotime("$end_date"); // or your date as well
     $your_date = strtotime("$today");
     $datediff = $now - $your_date;
	 
	 $datediff2 = $your_date-$now;
     $due_days=floor($datediff/(60*60*24));
	 $over_due_days=floor($datediff2/(60*60*24));
 
	 
	 if ($due_days<=14)
	 {
	  echo "<font color='#ff0000'>Balance Due!!</font>";
	 }
	 else
	 {
	 //echo "<font color='#109100'>".$due_days." Days</font>"; 
	 }
	  
	  
	  ?></td>
<td>
	<i><font size="-2">
	<?php $staff=$rows->user_id;
$sqlst="SELECT * FROM  users where user_id='$staff'";
$resultst= mysql_query($sqlst) or die ("Error $sqlst.".mysql_error());	
$rowst=mysql_fetch_object($resultst);	
echo $rowst->f_name;
	?>
	
	</font></i>
	
	</td>
    <td align="center"><a href="home.php?viewsubprojectlocation=viewsubprojectlocation&booking_id=<?php echo $rows->booking_id;?>&job_card_id=<?php echo $job_card_id;?>&invoice_id=<?php echo $rows->invoice_id;?>">View Invoice Details</a></td>
<td align="right"><a rel="facebox" href="cancel_approved_invoice_reason.php?job_card_id=<?php echo $rows->job_card_id;?>">Cancel Invoice</a></td>
	
   
    </tr>

  <?php 
  
  }
  
  ?>
  <tr bgcolor="#FFFFCC">
 
  <td></td>
  <td></td>
  <td></td>
   <td align="right"><strong><font size="+1" color="#ff0000"><?php echo number_format($job_card_ttl,2); ?></font></strong></td>
   <td align="right"><strong><font size="+1" color="#ff0000"><?php echo number_format($inv_ttl,2); ?></font></strong></td>
 <td></td>
 <td></td>
 <td></td>

   
  <td></td>
  <td></td>

  <td></td>
 
  
  </tr>
  <?php
  
  }
  
  else 
  
  {
  ?>
  
  <tr bgcolor="#FFFFCC" height="30"><td colspan="11" align="center"><font color="#ff0000"><strong>No Results found!!</strong></font></td></tr>
  
  <?php 
  
  
  }
  
  
  ?>
  
  </table>
   </td></tr>	 
  
  
  
  
  
  
</table>
</form>
<script type="text/javascript">
  Calendar.setup(
    {
      inputField  : "from",         // ID of the input field
      ifFormat    : " %Y-%m-%d  ",    // the date format
      button      : "from"       // ID of the button
    }
  );
  
  Calendar.setup(
    {
      inputField  : "to",         // ID of the input field
      ifFormat    : " %Y-%m-%d  ",    // the date format
      button      : "to"       // ID of the button
    }
  );
  
  
  
  </script> 
   <?php }?>