<?php 
include ('includes/session.php');
include('Connections/fundmaster.php');
$date_month=$_GET['payment_month'];

?>
<title>Safaricom - Outlet Visit Dashboard Report</title>
<script language="javascript" src="gen_validatorv31.js" type="text/javascript"></script>
<script type="text/javascript" src="calender/calendar.js"></script>
<script type="text/javascript" src="calender/lang/calendar-en.js"></script>
<script type="text/javascript" src="calender/calendar-setup.js"></script>
<link rel="stylesheet" href="csspr.css" type="text/css" />

<Style>
.error_strings{ font-family:Verdana; font-size:10px; color: #FF0000;}
</Style>

<style type="text/css">

@import url(calender/calendar-win2k-1.css);

</style>

<style type="text/css">
.table
{
border-collapse:collapse;
}
.table td, tr
{
border:1px solid black;
padding:3px;
}
</style>
<body onLoad="window.print();">
<table width="700" border="0" class="table" align="center">

<tr height="40"> <td colspan="16" align="center"><img src="images/logolpo.png" width="300" height="80"></td></tr>
<tr height="40"> <td colspan="16" align="center"><H2>JUBA STATIONERY AND PRINTING COMPANY LIMITED</H2></td></tr>
<tr bgcolor="#FFFFCC">
   
    <td colspan="9" height="30" align="center">
<H2>List Of Cash Sales Pending Approval</H2>
	
	</td>
	
    </tr>
 <tr  style="background:url(images/description.gif);" height="30" >
  
    <td align="center" width="150"><strong>Job Card No</strong></td>   
    <td align="center" width="150"><strong>Date Generated</strong></td>
<td align="center" width="300"><strong>Customer Name</strong></td>  
<td align="center" width="150"><strong>Sale Value (SSP)</strong></td> 
    <td align="center" width="150"><strong>Amount Paid (SSP)</strong></td>
	 <td align="center" width="150"><strong>Balance(SSP)</strong></td> 
	<!--<td align="center" width="150"><strong>Amount(Kshs)</strong></td>-->
	<td align="center" width="150"><strong>Balance Payment Date</strong></td>    
	 <td align="center" width="150"><strong>Balance Payment Alert</strong></td>
	<td align="center" width="150"><strong>Generated By</strong></td>    
  
   

    </tr>


 <?php 
 $job_card_ttl=0;
 $inv_ttl=0;
 $gnd_bal=0;
if (!isset($_POST['generate']))
{ 

 
$sql="SELECT * FROM job_cards where sale_type='cs' and approved_status='0' order by date_generated desc";
$results= mysql_query($sql) or die ("Error $sql.".mysql_error());
}
else
{
$location_id=$_POST['location_id'];
$date_from=$_POST['from'];
$date_to=$_POST['to'];
if ($location_id!=0 && $date_from=='' && $date_to=='')
{
$sql="SELECT * FROM job_cards where customer_id='$location_id' and sale_type='cs' and approved_status='0' order by date_generated desc";
$results= mysql_query($sql) or die ("Error $sql.".mysql_error());

}


elseif ($location_id==0 && $date_from!='' && $date_to!='')
{
$sql="SELECT * FROM job_cards where date_generated>='$date_from' and date_generated<='$date_to' and sale_type='cs' and approved_status='0' order by date_generated desc";
$results= mysql_query($sql) or die ("Error $sql.".mysql_error());
}

elseif ($location_id!=0 && $date_from!='' && $date_to!='')
{
$sql="SELECT * FROM job_cards WHERE customer_id='$location_id' and date_generated>='$date_from' and date_generated<='$date_to' and sale_type='cs' and approved_status='0'  AND job_card_id LIKE 
'%$settlement_name%' order by date_generated desc";
$results= mysql_query($sql) or die ("Error $sql.".mysql_error());
}
else
{
$sql="SELECT * FROM job_cards where sale_type='cs' and approved_status='0' order by date_generated desc";
$results= mysql_query($sql) or die ("Error $sql.".mysql_error());

}

}
if (mysql_num_rows($results) > 0)
						  {
							  $RowCounter=0;
							  while ($rows=mysql_fetch_object($results))
							  { 
							  
							  $RowCounter++;
							  if($RowCounter % 2==0)
{
echo '<tr bgcolor="#C0D7E5" height="25">';
}
else 
{
echo '<tr bgcolor="#FFFFCC" height="25" >';
}
 
 
 ?>

  
   

    <td><?php echo $job_card_id=$rows->job_card_id;?></td>
  
    <td><?php echo $rows->start_date;?></td>
    <td>
	<?php 
	 $customer_id=$rows->customer_id;
	
$sqllpdet="SELECT * from customer where customer_id='$customer_id'";
$resultslpdet= mysql_query($sqllpdet) or die ("Error $sqllpdet.".mysql_error());
$rowslpdet=mysql_fetch_object($resultslpdet);
	
	
	echo $rowslpdet->customer_name;?>
	
	
	</td>
    <td align="right"><?php include ('invoice_value.php');?></td>
    <td align="right">
	
	<?php include ('invoice_payment_value.php');?>
	
	
	</td>
   
	<td align="right">
	
	<?php
echo number_format($bal=$task_totals-$all_amnt_totals,2);


$gnd_bal=$gnd_bal+$bal;
	?>
	
	
	
	</td>
	

	
	
	
	<td align="center">
	<?php 
	
	echo $rows->bal_date;

	
	
	?></td>
	  <td><?php 
	  
	  
	  
	  //$invoice_id=$rows->job_card_id;
	  
$begin_date=$rows->start_date;
$end_date=$rows->bal_date;

$today=date('Y-m-d');
$now = strtotime("$end_date"); // or your date as well
     $your_date = strtotime("$today");
     $datediff = $now - $your_date;
	 
	 $datediff2 = $your_date-$now;
     $due_days=floor($datediff/(60*60*24));
	 $over_due_days=floor($datediff2/(60*60*24));
 
	 
	 if ($due_days<=14)
	 {
	  echo "<font color='#ff0000'>Balance Due!!</font>";
	 }
	 else
	 {
	 //echo "<font color='#109100'>".$due_days." Days</font>"; 
	 }
	  
	  
	  ?></td>
<td>
	<i><font size="-2">
	<?php $staff=$rows->user_id;
$sqlst="SELECT * FROM  users where user_id='$staff'";
$resultst= mysql_query($sqlst) or die ("Error $sqlst.".mysql_error());	
$rowst=mysql_fetch_object($resultst);	
echo $rowst->f_name;
	?>
	
	</font></i>
	
	</td>
	<!--<td align="center"><a href="home.php?viewcountries=viewcountries&job_card_id=<?php echo $rows->job_card_id;?>">View invoice Details</a></td>

  <td align="right"><a rel="facebox" href="cancel_submited_invoices.php?booking_id=<?php echo $rows->booking_id;?>&invoice_id=<?php echo $rows->invoice_id; ?>&job_card_id=<?php echo $rows->job_card_id;?>&invoice_amnt=<?php echo $grand_ttl ?>" onClick="return confirmDelete();">Cancel Invoice</a></td>

<td></td>-->
	
   
    </tr>

  <?php 
  
  }
  
  ?>
  <tr bgcolor="#FFFFCC">
 
  <td></td>
  <td></td>
  <td></td>
   <td align="right"><strong><font size="+1" color="#ff0000"><?php echo number_format($job_card_ttl,2); ?></font></strong></td>
   <td align="right"><strong><font size="+1" color="#ff0000"><?php echo number_format($dwn_ttl,2); ?></font></strong></td>
   <td align="right"><strong><font size="+1" color="#ff0000"><?php echo number_format($gnd_bal,2); ?></font></strong></td>
 <td></td>
 <td></td>


   
  <td></td>

 
  
  </tr>
  <?php
  
  }
  
  else 
  
  {
  ?>
  
  <tr bgcolor="#FFFFCC" height="30"><td colspan="11" align="center"><font color="#ff0000"><strong>No Results found!!</strong></font></td></tr>
  
  <?php 
  
  
  }
  
  
  ?>
  
  </table>
   </td></tr>	 
  
  
  
  
  
  
</table>
</body>


