<?php 
include ('includes/session.php');
include('Connections/fundmaster.php');
$date_month=$_GET['payment_month'];

header("Content-Type: application/vnd.ms-excel");
header("Content-Disposition: attachment;Filename=Canceled_Job_Cards_List.xls");
header("Expires: 0");
header("Cache-Control: must-revalidate, post-check=0, pre-check=0");

$date_month=$_GET['payment_month'];
$location_id=$_GET['location_id'];
$settlement_name=$_GET['settlement_name'];


?>
<title>Safaricom - Outlet Visit Dashboard Report</title>
<script language="javascript" src="gen_validatorv31.js" type="text/javascript"></script>
<script type="text/javascript" src="calender/calendar.js"></script>
<script type="text/javascript" src="calender/lang/calendar-en.js"></script>
<script type="text/javascript" src="calender/calendar-setup.js"></script>
<link rel="stylesheet" href="csspr.css" type="text/css" />

<Style>
.error_strings{ font-family:Verdana; font-size:10px; color: #FF0000;}
</Style>

<style type="text/css">

@import url(calender/calendar-win2k-1.css);

</style>

<style type="text/css">
.table
{
border-collapse:collapse;
}
.table td, tr
{
border:1px solid black;
padding:3px;
}
</style>
<body onLoad="window.print();">
<table width="100" border="1" class="table" align="center">


<tr height="40"> <td colspan="8" align="center"><H4>JUBA STATIONERY AND PRINTING COMPANY LIMITED</H4></td></tr>
<tr bgcolor="#FFFFCC">
   
    <td colspan="8" height="30" align="center">
<H5>List Of Job Cards Generated (Canceled)</H5>
	
	</td>
	
    </tr>
 <tr  style="background:url(images/description.gif);" height="30" >
 
   <td align="center" ><strong>Job Card No</strong></td>
    <td align="center" ><strong>Date Generated</strong></td>
	 <td align="center" ><strong>Customer Name</strong></td> 
	<td align="center" ><strong>Start Date</strong></td>
	<td align="center" ><strong>Completion Date</strong></td>
    <td align="center" ><strong>Period</strong></td>  	
    <td align="center" ><strong>Technician</strong></td>
    <td align="center" ><strong>Generated By</strong></td>  

    </tr>


  <?php 
if ($location_id!=0 && $settlement_name=='')
{
$sql="SELECT * FROM job_cards where customer_id='$location_id' and canceled_status='1' and approved_status='0' order by date_generated desc";
$results= mysql_query($sql) or die ("Error $sql.".mysql_error());

}

elseif ($location_id==0 && $settlement_name!='')
{
$sql="SELECT * FROM job_cards where job_card_id LIKE '%$settlement_name%' and canceled_status='1' and approved_status='0' order by date_generated desc";
$results= mysql_query($sql) or die ("Error $sql.".mysql_error());
}

elseif ($location_id!=0 && $settlement_name!='')
{
$sql="SELECT * FROM job_cards WHERE customer_id='$location_id' and canceled_status='1' and approved_status='0' AND job_card_id LIKE 
'%$settlement_name%' order by date_generated desc";
$results= mysql_query($sql) or die ("Error $sql.".mysql_error());
}
else
{
$sql="SELECT * FROM job_cards where canceled_status='1' and approved_status='0' order by date_generated desc";
$results= mysql_query($sql) or die ("Error $sql.".mysql_error());

}
if (mysql_num_rows($results) > 0)
						  {
							  $RowCounter=0;
							  while ($rows=mysql_fetch_object($results))
							  { 
							  
							  $RowCounter++;
							  if($RowCounter % 2==0)
{
echo '<tr bgcolor="#C0D7E5" height="25">';
}
else 
{
echo '<tr bgcolor="#FFFFCC" height="25" >';
}
 
 
 ?>
  
   
    <!--<td><?php echo $job_card_id=$rows->job_card_id;?></td>-->
    <td><?php echo $job_card_id=$rows->job_card_id;?></td>
    <td><?php echo $rows->start_date;?></td>
    <td>
	<?php 
	 $customer_id=$rows->customer_id;
	
$sqllpdet="SELECT * from customer where customer_id='$customer_id'";
$resultslpdet= mysql_query($sqllpdet) or die ("Error $sqllpdet.".mysql_error());
$rowslpdet=mysql_fetch_object($resultslpdet);
	
	
	echo $rowslpdet->customer_name;?>
	
	
	</td>
    <td align="center"><?php echo $reg_no=$rows->start_date;?></td>
    <td align="center">
	
	<?php echo $rows->end_date;?>
	
	
	</td>
    
	<td align="center">
	
	<?php
/* $sqlpt="SELECT * from released_item where job_card_id='$job_card_id'";
$resultspt= mysql_query($sqlpt) or die ("Error $sqlpt.".mysql_error());
echo $rowspt=mysql_num_rows($resultspt); */

//echo $rows->end_date;

$begin_date=$rows->start_date;
$end_date=$rows->end_date;

$today=date('Y-m-d');
$now = strtotime("$end_date"); // or your date as well
     $your_date = strtotime("$today");
     $datediff = $now - $your_date;
	 
	 $datediff2 = $your_date-$now;
     $due_days=floor($datediff/(60*60*24));
	 $over_due_days=floor($datediff2/(60*60*24));
 
	 
	 if ($due_days <0)
	 {
	  echo "<font color='#ff0000'>Over Due By ".$over_due_days. " Days</font>";
	 }
	 else
	 {
	 echo "<font color='#109100'>".$due_days." Days</font>"; 
	 }

	?>
	
	
	
	</td>
	

	
	
	
	<td>
	         <?php 
$techniacian_id=$rows->technician_id;
$sqluser="select * FROM users WHERE user_id='$techniacian_id'";
$resultsuser= mysql_query($sqluser) or die ("Error $sqluser.".mysql_error());
	
$rowsuser=mysql_fetch_object($resultsuser);	

echo $rowsuser->f_name;
	
	
	
	?>
	
	</strong></td>
	<td>
	<i><font size="-2">
	<?php $staff=$rows->user_id;
$sqlst="SELECT * FROM  users where user_id='$staff'";
$resultst= mysql_query($sqlst) or die ("Error $sqlst.".mysql_error());	
$rowst=mysql_fetch_object($resultst);	
echo $rowst->f_name;
	?>
	
	</font></i>
	
	</td>

<!--<td></td>-->
	
   
    </tr>

  <?php 
  
  }
  
  }
  
  else 
  
  {
  ?>
  
  <tr bgcolor="#FFFFCC" height="30"><td colspan="11" align="center"><font color="#ff0000"><strong>No Results found!!</strong></font></td></tr>
  
  <?php 
  
  
  }
  
  
  ?>
  
  </table>
   </td></tr>	 
  
  
  
  
  
  
</table>
</body>


