<?php 
include ('includes/session.php');
include('Connections/fundmaster.php');

$supplier=$_GET['location_id'];
$shop_id=$_GET['shop_id'];
$date_from=$_GET['from'];
$date_to=$_GET['to'];
$sale_type=$_GET['sale_type'];

$querycont="select * from company_contacts order by contacts_id desc limit 1";
$resultscont=mysql_query($querycont) or die ("Error: $querycont.".mysql_error());
$rowscont=mysql_fetch_object($resultscont); 

?>
<title>Safaricom - Outlet Visit Dashboard Report</title>
<script language="javascript" src="gen_validatorv31.js" type="text/javascript"></script>
<script type="text/javascript" src="calender/calendar.js"></script>
<script type="text/javascript" src="calender/lang/calendar-en.js"></script>
<script type="text/javascript" src="calender/calendar-setup.js"></script>
<link rel="stylesheet" href="csspr.css" type="text/css" />

<Style>
.error_strings{ font-family:Verdana; font-size:10px; color: #FF0000;}
</Style>

<style type="text/css">

@import url(calender/calendar-win2k-1.css);

</style>

<style type="text/css">
.table
{
border-collapse:collapse;
}
.table td, tr
{
border:1px solid black;
padding:3px;
}
</style>
<body onLoad="window.print();">
<table width="700" border="0" class="table" align="center">

<tr height="40"> <td colspan="16" align="center"><img src="images/logolpo.png" width="300" height="80"></td></tr>
<tr height="40"> <td colspan="16" align="center"><H2><?php echo $rowscont->cont_person; ?></H2></td></tr>
<tr bgcolor="#FFFFCC">
   
    <td colspan="13" height="30" align="center">
<H2>Sales Report Per Item</H2>
	
	</td>
	
    </tr>

  
    <tr  style="background:url(images/description.gif);" height="30" >
  
    <td align="center" width="150"><strong>Invoice No</strong></td>   

<td align="center" width="150"><strong>Sales Type</strong></td>   
<td align="center" width="150"><strong>Sales Date</strong></td>
<td align="center" width="150"><strong>Item Name</strong></td> 
<td align="center" width="150"><strong>Quantity</strong></td> 
<td align="center" width="150"><strong>Item Cost</strong></td>
<td align="center" width="150"><strong>Total Cost</strong></td>
<td align="center" width="150"><strong>Selling Price</strong></td> 
<td align="center" width="150"><strong>Total Sales</strong></td> 
<td align="center" width="150"><strong>Discount</strong></td> 
<td align="center" width="150"><strong>Final Sales</strong></td> 
<td align="center" width="150"><strong>Profit</strong></td> 
<td align="center" width="150"><strong>Generated By</strong></td>   
   

    </tr>


<?php 
 $job_card_ttl=0;
 $inv_ttl=0;
 $gnd_bal=0;
 
 

 



$querydc= "SELECT * FROM sales,sales_item,items";
    $conditions = array();
    if($supplier!=0) 
	
	{
	
    $conditions[] = "sales_item.item_id='$supplier'";
	
    }
	

	
	if($sale_type!='') 
	{
	
    $conditions[] = " sales.sale_type='$sale_type'";
	  
    }
	

	if($date_from!='' && $date_to!='' ) {
	
       $conditions[] = " sales.sale_date >='$date_from' AND sales.sale_date<='$date_to' ";
    }
	
	
	

    //$sql = $query;
    if (count($conditions) > 0) {
      $querydc .= " WHERE " . implode(' AND ', $conditions)." AND sales.sales_id=sales_item.sales_id AND canceled_status='0' AND  
sales_item.item_id=items.item_id order by sales.date_generated desc";
    }
	else
	{	
	
$querydc="SELECT * FROM sales,sales_item,items where sales.sales_id=sales_item.sales_id AND canceled_status='0' AND  sales_item.item_id=items.item_id order by sales.date_generated desc";
$resultsdc= mysql_query($querydc) or die ("Error $querydc.".mysql_error());

	}

    $resultsdc = mysql_query($querydc) or die ("Error $querydc.".mysql_error());



 
if (mysql_num_rows($resultsdc) > 0)
						  {
							  $RowCounter=0;
							  while ($rows=mysql_fetch_object($resultsdc))
							  { 
							  
							  $RowCounter++;
							  if($RowCounter % 2==0)
{
echo '<tr bgcolor="#C0D7E5" height="25">';
}
else 
{
echo '<tr bgcolor="#FFFFCC" height="25" >';
}
 
 
 ?>

  
   
<td><?php echo $inv_no=$rows->invoice_no;
	
	$job_card_id=$rows->sales_id;
	
	
	?></td>
  
  
    <td><?php 
	
	$type=$rows->sale_type; 
  
  if ($type=='cr')
  {
  echo "Credit Sales/Invoice";
  }
  
if ($type=='cs')
  {
    echo "Cash Sales";
  }
  else
  {
  
  
  }
	
	
	//echo $rows->sale_date;?></td>
    <td><?php 
  
 echo $rows->sale_date;
  
  
  ?></td>
    <td>
	<?php 
	
	
	 /* $customer_id=$rows->customer_id;
	
$sqllpdet="SELECT * from customer where customer_id='$customer_id'";
$resultslpdet= mysql_query($sqllpdet) or die ("Error $sqllpdet.".mysql_error());
$rowslpdet=mysql_fetch_object($resultslpdet); */
	
	
	echo $rows->item_name;?>
	
	
	</td>
    <td align="right"><?php
echo $item_quantity=$rows->item_quantity;

$ttl_quant=$ttl_quant+$item_quantity;

	//include ('invoice_value.php');
	
	
	?></td>
    <td align="right">
	
	<?php //include ('invoice_payment_value.php');
	
	echo number_format($curr_bp=$rows->curr_bp,2);
	
	
	
	?>
	
	
	</td>
		<td align="right">
	
	<?php //include ('invoice_payment_value.php');
	
	echo number_format($ttl_cost=$curr_bp*$item_quantity,2);
	
	$job_card_ttl=$job_card_ttl+$ttl_cost;
	
	?>
	
	
	</td>
	
	
	
	<td align="right">
	
	<?php //include ('invoice_payment_value.php');
	
	echo number_format($sp=$rows->item_cost,2);
	
	
	
	?>
	
	
	</td>

	
	<td align="right">
	
	<?php //include ('invoice_payment_value.php');
	
	echo number_format($ttl_sales=$sp*$item_quantity,2);
	
	
	$ttl_presale=$ttl_presale+$ttl_sales;
	
	
	?>
	
	
	</td>
	<td align="center"><?php
$item_disc=$rows->shop_id;

	echo number_format($item_disc,2); 
	echo "%";
	
	$disc_value=$item_disc*$ttl_sales/100;
	
	echo "<span style='float:right;'>".number_format($disc_value,2);
	
	echo "</span>";
	$ttl_disc=$ttl_disc+$disc_value;
	?></td>
	<td align="right"><?php echo number_format($final_sales=$ttl_sales-$disc_value,2); 
$dwn_ttl=$dwn_ttl+$final_sales;	
	
	?></td>
   
	<td align="right">
	
	<?php
echo number_format($ttl_profit=$final_sales-$ttl_cost,2);


$gnd_bal=$gnd_bal+$ttl_profit;
	?>
	
	
	
	</td>
	
	
	

	
	
	
	
<td>
	<i><font size="-2">
	<?php $staff=$rows->user_id;
$sqlst="SELECT * FROM  users where user_id='$staff'";
$resultst= mysql_query($sqlst) or die ("Error $sqlst.".mysql_error());	
$rowst=mysql_fetch_object($resultst);	
echo $rowst->f_name;
	?>
	
	</font></i>
	
	</td>
	
 <!--
 <td align="right"><a rel="facebox" href="cancel_submited_invoices.php?sales_id=<?php echo $rows->sales_id;?>" onClick="return confirmDelete();">Cancel Invoice</a></td>

<td></td>-->
	
   
    </tr>

  <?php 
  
  }
  
  ?>
  <tr bgcolor="#FFFFCC">
 
  <td></td>
  <td></td>
  <td></td>
  <td></td>

<td align="right"><strong><?php echo number_format($ttl_quant,2); ?></strong></td>
	  <td></td>
  <td align="right"><strong><font size="+1" color="#ff0000"><?php echo number_format($job_card_ttl,2); ?></font></strong></td>
   <td></td>
 <td align="right"><strong><?php echo number_format($ttl_presale,2); ?></strong></td>

     <td align="right"><strong><?php echo number_format($ttl_disc,2); ?></strong></td>
  <td align="right"><strong><font size="+1" color="#ff0000"><?php echo number_format($dwn_ttl,2); ?></font></strong></td>
  <td align="right"><strong><font size="+1" color="#ff0000"><?php echo number_format($gnd_bal,2); ?></font></strong></td>
 <td></td>



 
  
  </tr>
  <?php
  
  }
  
  else 
  
  {
  ?>
  
  <tr bgcolor="#FFFFCC" height="30"><td colspan="11" align="center"><font color="#ff0000"><strong>No Results found!!</strong></font></td></tr>
  
  <?php 
  
  
  }
  
  
  ?>
  
  </table>
   </td></tr>	 
  
  
  
  
  
  
</table>
</body>


