<?php 
include ('includes/session.php');
include('Connections/fundmaster.php');
$supplier=$_GET['location_id'];
$shop_id=$_GET['shop_id'];
$date_from=$_GET['from'];
$date_to=$_GET['to'];

$querycont="select * from company_contacts order by contacts_id desc limit 1";
$resultscont=mysql_query($querycont) or die ("Error: $querycont.".mysql_error());
$rowscont=mysql_fetch_object($resultscont); 

?>
<title>Safaricom - Outlet Visit Dashboard Report</title>
<script language="javascript" src="gen_validatorv31.js" type="text/javascript"></script>
<script type="text/javascript" src="calender/calendar.js"></script>
<script type="text/javascript" src="calender/lang/calendar-en.js"></script>
<script type="text/javascript" src="calender/calendar-setup.js"></script>
<link rel="stylesheet" href="csspr.css" type="text/css" />

<Style>
.error_strings{ font-family:Verdana; font-size:10px; color: #FF0000;}
</Style>

<style type="text/css">

@import url(calender/calendar-win2k-1.css);

</style>

<style type="text/css">
.table
{
border-collapse:collapse;
}
.table td, tr
{
border:1px solid black;
padding:3px;
}
</style>
<body onLoad="window.print();">
<table width="700" border="0" class="table" align="center">

<tr height="40"> <td colspan="16" align="center"><img src="images/logolpo.png" width="300" height="80"></td></tr>
<tr height="40"> <td colspan="16" align="center"><H2><?php echo $rowscont->cont_person; ?></H2></td></tr>
<tr bgcolor="#FFFFCC">
   
    <td colspan="9" height="30" align="center">
<H2>Sales Summary Report</H2>
	
	</td>
	
    </tr>

  
    <tr  style="background:url(images/description.gif);" height="30" >
  
     <td align="center" width="150"><strong>Invoice No</strong></td>   
    <td align="center" width="150"><strong>Sales Type</strong></td>   
    <td align="center" width="150"><strong>Sales Date</strong></td>
<td align="center" width="300"><strong>Customer Name</strong></td>  
<td align="center" width="150"><strong>Invoice Value (Kshs)</strong></td> 
    <td align="center" width="150"><strong>Amount Paid (Kshs)</strong></td>
<td align="center" width="150"><strong>Balance(Kshs)</strong></td> 

	<td align="center" width="150"><strong>Generated By</strong></td>    
   

    </tr>


 <?php 
 $job_card_ttl=0;
 $inv_ttl=0;
 $gnd_bal=0;
 
 if ($user_group_id==15)

 {

 


$querydc= "SELECT * FROM sales";
    $conditions = array();
    if($supplier!=0) 
	
	{
	
    $conditions[] = "sales.customer_id='$supplier'";
	
    }
	

	

	if($date_from!='' && $date_to!='' )
	 {
	
       $conditions[] = "sales.sale_date>='$date_from' AND sales.sale_date<='$date_to'";
    }
	
	
	

    //$sql = $query;
    if (count($conditions) > 0) {
      $querydc .= " WHERE " . implode(' AND ', $conditions)." AND sale_type='cr' and canceled_status='0' order by sales_id desc";
    }
	else
	{	
	
$querydc="SELECT * FROM sales where sale_type='cr' and canceled_status='0' order by sales_id desc";
$resultsdc= mysql_query($querydc) or die ("Error $querydc.".mysql_error());

	}

    $resultsdc = mysql_query($querydc) or die ("Error $querydc.".mysql_error());


}

 ////send of super dmin
 else
	 
	 {
		 

$supplier=$_POST['location_id'];
$shop_id=$_POST['shop_id'];
echo $date_from=$_POST['from'];
echo $date_to=$_POST['to'];

$querydc= "SELECT * FROM sales";
    $conditions = array();
    if($supplier!=0) 
	
	{
	
    $conditions[] = "sales.customer_id='$supplier'";
	
    }
	

	

	if($date_from!='' && $date_to!='' ) {
	
       $conditions[] = " sales.sale_date>='$date_from' AND sales.sale_date<='$date_to'";
    }
	
	
	

    //$sql = $query;
    if (count($conditions) > 0) {
      $querydc .= " WHERE " . implode(' AND ', $conditions)." AND sales_rep='$user_id' order by sales_id desc";
    }
	else
	{	
	
$querydc="SELECT * FROM sales where sales_rep='$user_id' order by sales_id desc";
$resultsdc= mysql_query($querydc) or die ("Error $querydc.".mysql_error());

	}

    $resultsdc = mysql_query($querydc) or die ("Error $querydc.".mysql_error());


}	 
		 
		 



if (mysql_num_rows($resultsdc) > 0)
						  {
							  $RowCounter=0;
							  while ($rows=mysql_fetch_object($resultsdc))
							  { 
							  
							  $RowCounter++;
							  if($RowCounter % 2==0)
{
echo '<tr bgcolor="#C0D7E5" height="25">';
}
else 
{
echo '<tr bgcolor="#FFFFCC" height="25" >';
}
 
 
 
 ?>

  
   

    <td><?php $job_card_id=$rows->sales_id;
	
	echo $rows->invoice_no;
	
	?></td>
   
  
    <td><?php echo $rows->sale_date;?></td>
    <td><?php 
  $type=$rows->sale_type; 
  
  if ($type=='cr')
  {
  echo "Credit Sales/Invoice";
  }
  
if ($type=='cs')
  {
    echo "Cash Sales";
  }
  else
  {
  
  
  }
  
  
  
  ?></td>
    <td>
	<?php 
	 $customer_id=$rows->customer_id;
	
$sqllpdet="SELECT * from customer where customer_id='$customer_id'";
$resultslpdet= mysql_query($sqllpdet) or die ("Error $sqllpdet.".mysql_error());
$rowslpdet=mysql_fetch_object($resultslpdet);
	
	
	echo $rowslpdet->customer_name;?>
	
	
	</td>
    <td align="right"><?php include ('invoice_value.php');?></td>
    <td align="right">
	
	<?php include ('invoice_payment_value.php');
	
	$grnd_inv_payment=$grnd_inv_payment+$all_amnt_totals;	
	
	?>
	
	
	</td>
   
	<td align="right">

<?php
echo number_format($bal=$task_totals-$all_amnt_totals,2);


$gnd_bal=$gnd_bal+$bal;
	?>

	
	
	
	</td>
	

	
	
	
	
<td>
	<i><font size="-2">
	<?php $staff=$rows->user_id;
$sqlst="SELECT * FROM  users where user_id='$staff'";
$resultst= mysql_query($sqlst) or die ("Error $sqlst.".mysql_error());	
$rowst=mysql_fetch_object($resultst);	
echo $rowst->f_name;
	?>
	
	</font></i>
	
	</td>
	
 <!--
 <td align="right"><a rel="facebox" href="cancel_submited_invoices.php?sales_id=<?php echo $rows->sales_id;?>" onClick="return confirmDelete();">Cancel Invoice</a></td>

<td></td>-->
	
   
    </tr>

  <?php 
  
  }
  
  ?>
  <tr bgcolor="#FFFFCC">
 
  <td></td>

  <td></td>
  <td></td>
    <td></td>
  <td align="right"><strong><font size="+1" color="#ff0000"><?php echo number_format($job_card_ttl,2); ?></font></strong></td>
  <td align="right"><strong><font size="+1" color="#ff0000"><?php echo number_format($grnd_inv_payment,2); ?></font></strong></td>
  <td align="right"><strong><font size="+1" color="#ff0000"><?php echo number_format($gnd_bal,2); ?></font></strong></td>
 <td></td>



   



 
  
  </tr>
  <?php
  
  }
  
  else 
  
  {
  ?>
  
  <tr bgcolor="#FFFFCC" height="30"><td colspan="11" align="center"><font color="#ff0000"><strong>No Results found!!</strong></font></td></tr>
  
  <?php 
  
  
  }
  
  
  ?>
  
  </table>
   </td></tr>	 
  
  
  
  
  
  
</table>
</body>


