<?php

if ($sess_allow_view==0)
{
include ('includes/restricted.php');
}
else
{
 ?><?php
if(isset($_GET['subDELETEsettlement']))
  { 
$settlement_id=$_GET['settlement_id'];
 delete_settlement($settlement_id);
  }
  
 
?>
<script type="text/javascript" src="calender/calendar.js"></script>
<script type="text/javascript" src="calender/lang/calendar-en.js"></script>
<script type="text/javascript" src="calender/calendar-setup.js"></script>
<style type="text/css">

@import url(calender/calendar-win2k-1.css);

</style>
<script type="text/javascript"> 

function confirmDelete()
{
    return confirm("Are you sure you want to delete?");
}

</script>


<form name="search" method="post" action=""> 
<table width="100%" border="0">
  <tr bgcolor="#FFFFCC">
   
    <td colspan="11" height="30" align="center"> 
	<?php

if ($_GET['updateuserconfirm']==1)
echo '<div align="center" style="background: #FFCC33; height:20px; width:550px; border:#FF0000 solid 1px; font-size:11px;" class="br-5"> <p align="center"><font color="#FF0000" >User Updated Successfully!!</font></strong></p></div>';
?> 

<?php 

if ($_GET['deleteconfirm']==1)
echo '<div align="center" style="background: #FFCC33; height:20px; width:550px; border:#FF0000 solid 1px; font-size:11px;" class="br-5"> <p align="center"><font color="#FF0000" >Record Deleted Successfully!!</font></strong></p></div>';
?>
	
	</td>
	
    </tr>
	<tr height="30" bgcolor="#FFFFCC">
     <td width="23%" colspan="11" align="center">   <strong>Filter By Job Card Number<font color="#FF0000">* </font></strong>
	<select name="location_id"><option value="0">Select..........................................................</option>
								  <?php
								  
								  $query1="select job_card_id from requisition order by job_card_id asc";
								  $results1=mysql_query($query1) or die ("Error: $query1.".mysql_error());
								  
								  if (mysql_num_rows($results1)>0)
								  
								  {
									  while ($rows1=mysql_fetch_object($results1))
									  
									  { ?>
										  
                                    <option value="<?php echo $rows1->job_card_id;?>"><?php echo $rows1->job_card_id; ?> </option>
                                    
                                
										  
										<?php  }
									  
									  
									  }
									  
									  
								  
								  
								  
								  
								  
								  ?></select>
								  
								  
								  <strong>Or By Date</strong>
						<strong>From : </strong><input type="text" name="date_from" size="30" id="date_from" readonly="readonly" /><strong>To:</strong>
		<input type="text" name="date_to" size="25" id="date_to" readonly="readonly" />			  
								  
<input type="submit" name="generate" value="Generate">								  
								  
								  </td>
    
  </tr>
  
  <tr  style="background:url(images/description.gif);" height="30" >
  
   <td align="center" width="150"><strong>Requisition No</strong></td>
    <td align="center" width="150"><strong>Job Card No</strong></td>
    <td align="center" width="150"><strong>Date Generated</strong></td>
    <td align="center" width="150"><strong>Make and Model</strong></td>
	 <td align="center" width="150"><strong>Registration No</strong></td>
    <td align="center" width="150"><strong>Customer Name</strong></td>   

 
    <td align="center" width="150"><strong>Generated By</strong></td>    
    <td align="center" width="150"><strong>Release Items</strong></td>    

    </tr>


 <?php 
if ($user_group_id==15)
{
  if (!isset($_POST['generate']))
{ 

 
$sql="SELECT * FROM requisition order by date_generated desc";
$results= mysql_query($sql) or die ("Error $sql.".mysql_error());
}
else
{
$location_id=$_POST['location_id'];
$date_from=$_POST['date_from'];
$date_to=$_POST['date_to'];
if ($location_id!=0 && $date_from=='' && $date_to=='')
{
$sql="SELECT * FROM requisition where job_card_id='$location_id' order by date_generated desc";
$results= mysql_query($sql) or die ("Error $sql.".mysql_error());

}

elseif ($location_id==0 && $date_from!='' && $date_to!='')
{
$sql="SELECT * FROM requisition where date_generated>='$date_from' AND date_generated<='$date_to' order by date_generated desc";
$results= mysql_query($sql) or die ("Error $sql.".mysql_error());
}

elseif ($location_id!=0 && $date_from!='' && $date_to!='')
{
$sql="SELECT * FROM requisition where date_generated>='$date_from' AND date_generated<='$date_to' AND job_card_id='$location_id' order by date_generated desc";
$results= mysql_query($sql) or die ("Error $sql.".mysql_error());
}
else
{
$sql="SELECT * FROM requisition order by date_generated desc";
$results= mysql_query($sql) or die ("Error $sql.".mysql_error());

}




}
}
else
{

  if (!isset($_POST['generate']))
{ 

 
$sql="SELECT * FROM requisition order by date_generated desc";
$results= mysql_query($sql) or die ("Error $sql.".mysql_error());
}
else
{
$location_id=$_POST['location_id'];
$settlement_name=$_POST['settlement_name'];
if ($location_id!=0 && $settlement_name=='')
{
$sql="SELECT * FROM requisition where customer_id='$location_id' order by date_generated desc";
$results= mysql_query($sql) or die ("Error $sql.".mysql_error());

}

elseif ($location_id==0 && $settlement_name!='')
{
$sql="SELECT * FROM requisition,bookings where requisition.booking_id=bookings.booking_id AND bookings.reg_no LIKE '%$settlement_name%' order by date_generated desc";
$results= mysql_query($sql) or die ("Error $sql.".mysql_error());
}

elseif ($location_id!=0 && $settlement_name!='')
{
$sql="SELECT * FROM requisition,bookings where requisition.booking_id=bookings.booking_id AND requisition.customer_id='$location_id' AND bookings.reg_no LIKE 
'%$settlement_name%' order by date_generated desc";
$results= mysql_query($sql) or die ("Error $sql.".mysql_error());
}
else
{
$sql="SELECT * FROM requisition order by date_generated desc";
$results= mysql_query($sql) or die ("Error $sql.".mysql_error());

}




}




}
if (mysql_num_rows($results) > 0)
						  {
							  $RowCounter=0;
							  while ($rows=mysql_fetch_object($results))
							  { 
							  
							  $RowCounter++;
							  if($RowCounter % 2==0)
{
echo '<tr bgcolor="#C0D7E5" height="25">';
}
else 
{
echo '<tr bgcolor="#FFFFCC" height="25" >';
}
 
 
 ?>
  
   
  
    <td><?php echo $requisition_id=$rows->requisition_id;?></td>
	 <td><?php echo $job_card_id=$rows->job_card_id;?></td>
    <td><?php echo $rows->date_generated;?></td>
    <td>
	<?php 
	 $booking_id=$rows->booking_id;
	
$sqllpdet="SELECT * from bookings,customer where bookings.customer_id=customer.customer_id AND booking_id='$booking_id'";
$resultslpdet= mysql_query($sqllpdet) or die ("Error $sqllpdet.".mysql_error());
$rowslpdet=mysql_fetch_object($resultslpdet);
	
	
	echo $rowslpdet->vehicle_make.' - '.$rowslpdet->vehicle_model;?>
	
	
	</td>
    <td align="center"><?php echo $reg_no=$rowslpdet->reg_no;?></td>
    <td>
	
	<?php echo $rowslpdet->customer_name;?>
	
	
	</td>
    
	
	

	
	
	
	
	<td>
	<i><font size="-2">
	<?php $staff=$rows->user_id;
$sqlst="SELECT * FROM  users where user_id='$staff'";
$resultst= mysql_query($sqlst) or die ("Error $sqlst.".mysql_error());	
$rowst=mysql_fetch_object($resultst);	
echo $rowst->f_name;
	?>
	
	</font></i>
	
	</td>
  <td align="center">
  <?php
$sqlredx="SELECT SUM(item_quantity) AS item_req from requisition_item where requisition_id='$requisition_id'";
$resultsredx= mysql_query($sqlredx) or die ("Error $sqlredx.".mysql_error());
$rowsredx=mysql_fetch_object($resultsredx);
$qnty_ordered=$rowsredx->item_req;


$sqlord1="select SUM(released_quantity) as ttl_quant_rec from released_item where requisition_id='$requisition_id'";
$resultsord1= mysql_query($sqlord1) or die ("Error $sqlord1.".mysql_error());
$rowsord1=mysql_fetch_object($resultsord1);
$qnty_rel=$rowsord1->ttl_quant_rec;


if ($qnty_ordered==$qnty_rel)
	{
	//echo "Received All";
	?>
	
	<a href="release_items_from_store.php?requisition_id=<?php echo $rows->requisition_id; ?>"><font color="#ff0000"><strong>All Items Released</strong></font></a>
	<?php
	}
	elseif($qnty_ordered > $qnty_rel && $qnty_rel!='')
	{
	?>
	<a href="release_items_from_store.php?requisition_id=<?php echo $rows->requisition_id; ?>"><font color="#003399"><strong>Release Remaining Items</strong></font></a>
	<?php 
	
	}
	
	else
	{
	
	?>
	
	<a href="release_items_from_store.php?requisition_id=<?php echo $rows->requisition_id; ?>"><font color="#006600"><strong>Release Items</strong></font></a>
	<?php
	
	}


	?>


  
  
  <!--<a href="release_items_from_store.php?requisition_id=<?php echo $rows->requisition_id; ?>">Release Items</a>-->
  
  </td>

<!--<td></td>-->
	
   
    </tr>

  <?php 
  
  }
  
  }
  
  else 
  
  {
  ?>
  
  <tr bgcolor="#FFFFCC" height="30"><td colspan="11" align="center"><font color="#ff0000"><strong>No Results found!!</strong></font></td></tr>
  
  <?php 
  
  
  }
  
  
  ?>
  
  </table>
   </td></tr>	 
  
  
  
  
  
  
</table>
</form>

<script type="text/javascript">
  Calendar.setup(
    {
      inputField  : "date_from",         // ID of the input field
      ifFormat    : " %Y-%m-%d  ",    // the date format
      button      : "date_from"       // ID of the button
    }
  );
  
  Calendar.setup(
    {
      inputField  : "date_to",         // ID of the input field
      ifFormat    : " %Y-%m-%d  ",    // the date format
      button      : "date_to"       // ID of the button
    }
  );
  
  
  
  </script> 
 <?php }?>