<?php

if ($sess_allow_view==0)
{
include ('includes/restricted.php');
}
else
{
 ?><?php
if(isset($_GET['subDELETEsettlement']))
  { 
$settlement_id=$_GET['settlement_id'];
 delete_settlement($settlement_id);
  }
  
$supplier=$_POST['location_id'];
$shop_id=$_POST['shop_id'];
$date_from=$_POST['from'];
$date_to=$_POST['to'];
?>

<script type="text/javascript"> 

function confirmDelete()
{
    return confirm("Are you sure you want to cancel this invoice?");
}

</script>

<script src="js/jquery-1.12.4.js"></script>
 <script src="js/jquery.dataTables.min.js"></script>
 <script src="js/dataTables.buttons.min.js"></script>
 <script src="js/jszip.min.js"></script>
 <script src="js/pdfmake.min.js"></script>
 <script src="js/buttons.html5.min.js"></script>
 <script src="js/buttons.print.min.js"></script>
 <link rel="stylesheet" href="css/jquery.dataTables.min.css">
 <link rel="stylesheet" href="css/buttons.dataTables.min.css">
  <script>
 $(document).ready(function() {
    $('#example').DataTable( {
        dom: 'Bfrtip',
        buttons: [
            'copy', 'csv', 'excel', 'pdf', 'print'
        ]
    } );
} );
 </script>



<form name="search" method="post" action=""> 
<table width="98%" border="0" align="center" bgcolor="#9AD7AF" class="display nowrap" style="border-radius:5px;" id="example">	

    <thead>
  
  <tr  style="background:url(images/description.gif);" height="30" >
  
    <td align="center" width="150"><strong>Invoice No</strong></td>   

    <td align="center" width="150"><strong>Sales Date</strong></td>
<td align="center" width="300"><strong>Customer Name</strong></td>  
<td align="center" width="150"><strong>Invoice Value </strong></td> 
    <td align="center" width="150"><strong>Amount Paid</strong></td>
<td align="center" width="150"><strong>Balance</strong></td> 

	<td align="center" width="150"><strong>Generated By</strong></td>    
	<td align="center" width="150"><strong>Sales Rep</strong></td>    
	<td align="center" width="150"><strong>Sale Type</strong></td>   
    <td align="center" width="150"><strong>View Details</strong></td>
  

    </tr>
  	  </thead>

 <?php 
 $job_card_ttl=0;
 $inv_ttl=0;
 $gnd_bal=0;
 
 if ($user_group_id==15 || $user_group_id==34)

 {

 
 if (!isset($_POST['generate']))
{

$querydc="SELECT * FROM sales where canceled_status='0' order by sales_id desc";
$resultsdc= mysql_query($querydc) or die ("Error $sql.".mysql_error());
}
else
{
$supplier=$_POST['location_id'];
$shop_id=$_POST['shop_id'];
echo $date_from=$_POST['from'];
echo $date_to=$_POST['to'];

$querydc= "SELECT * FROM sales";
    $conditions = array();
    if($supplier!=0) 
	
	{
	
    $conditions[] = "sales.customer_id='$supplier'";
	
    }
	

	

	if($date_from!='' && $date_to!='' ) {
	
       $conditions[] = " sales.sale_date>='$date_from' AND sales.sale_date<='$date_to'";
    }
	
	
	

    //$sql = $query;
    if (count($conditions) > 0) {
      $querydc .= " WHERE " . implode(' AND ', $conditions)." and sale_type='cr' and canceled_status='0' order by sales_id desc";
    }
	else
	{	
	
$querydc="SELECT * FROM sales and canceled_status='0' order by sales_id desc";
$resultsdc= mysql_query($querydc) or die ("Error $querydc.".mysql_error());

	}

    $resultsdc = mysql_query($querydc) or die ("Error $querydc.".mysql_error());


}

 }
 ////send of super dmin
 else
	 
	 {
		 
	if (!isset($_POST['generate']))
{

$querydc="SELECT * FROM sales where sale_type='cr' AND sales_rep='$user_id' order by sales_id desc";
$resultsdc= mysql_query($querydc) or die ("Error $sql.".mysql_error());
}
else
{
$supplier=$_POST['location_id'];
$shop_id=$_POST['shop_id'];
echo $date_from=$_POST['from'];
echo $date_to=$_POST['to'];

$querydc= "SELECT * FROM sales";
    $conditions = array();
    if($supplier!=0) 
	
	{
	
    $conditions[] = "sales.customer_id='$supplier'";
	
    }
	

	

	if($date_from!='' && $date_to!='' ) {
	
       $conditions[] = " sales.sale_date>='$date_from' AND sales.sale_date<='$date_to'";
    }
	
	
	

    //$sql = $query;
    if (count($conditions) > 0) {
      $querydc .= " WHERE " . implode(' AND ', $conditions)." AND sales_rep='$user_id' order by sales_id desc";
    }
	else
	{	
	
$querydc="SELECT * FROM sales where sales_rep='$user_id' order by sales_id desc";
$resultsdc= mysql_query($querydc) or die ("Error $querydc.".mysql_error());

	}

    $resultsdc = mysql_query($querydc) or die ("Error $querydc.".mysql_error());


}	 
		 
		 
		 
		 
		 
		 
		 
		 
		 
	 }
 


if (mysql_num_rows($resultsdc) > 0)
						  {
							  $RowCounter=0;
							  while ($rows=mysql_fetch_object($resultsdc))
							  { 
							  
							  $RowCounter++;
							  if($RowCounter % 2==0)
{
echo '<tr bgcolor="#C0D7E5" height="25">';
}
else 
{
echo '<tr bgcolor="#FFFFCC" height="25" >';
}
 
 
 ?>

  
   

<?php $job_card_id=$rows->sales_id;?>
    <td>
	<a style="font-weight:bold; color:#000; text-decoration:none;" href="generate_invoice.php?sales_id=<?php echo $rows->sales_id;?>">
	
	<?php echo $invoice_no=$rows->invoice_no;?></a></td>
    <!--<td><?php 

	$shop_id=$rows->shop_id;
	
	
	
$sqlsp="select * from account where account_id='$shop_id'";
$resultsp= mysql_query($sqlsp) or die ("Error $sqlsp.".mysql_error());
$row=mysql_fetch_object($resultsp);

echo $row->account_name;
	
	
	
	?></td>-->
  
    <td><?php echo $rows->sale_date;?></td>
    <td>
	<?php 
	 $customer_id=$rows->customer_id;
	
$sqllpdet="SELECT * from customer where customer_id='$customer_id'";
$resultslpdet= mysql_query($sqllpdet) or die ("Error $sqllpdet.".mysql_error());
$rowslpdet=mysql_fetch_object($resultslpdet);
	
	
	echo $rowslpdet->customer_name;?>
	
	
	</td>
    <td align="right"><?php include ('invoice_value.php');?></td>
    <td align="right">
	
	<?php include ('invoice_payment_value.php');
	$grnd_inv_payment=$grnd_inv_payment+$all_amnt_totals;
	
	?>
	
	
	</td>
   
	<td align="right">
	
	<?php
echo number_format($bal=$task_totals-$all_amnt_totals,2);


$gnd_bal=$gnd_bal+$bal;
	?>
	
	
	
	</td>
	

	
	
	
	
<td>
	<i><font size="-2">
	<?php $gen_by=$rows->user_id;
$sqlst="SELECT * FROM  users where user_id='$gen_by'";
$resultst= mysql_query($sqlst) or die ("Error $sqlst.".mysql_error());	
$rowst=mysql_fetch_object($resultst);	
echo $rowst->f_name;
	?>
	
	</font></i>
	
	</td>
	
	<td>
	<i><font size="-2">
	<?php $staff=$rows->sales_rep;
$sqlst="SELECT * FROM  users where user_id='$staff'";
$resultst= mysql_query($sqlst) or die ("Error $sqlst.".mysql_error());	
$rowst=mysql_fetch_object($resultst);	
echo $rowst->f_name;
	?>
	
	</font></i>
	
	</td>
		<td>
	<i><font size="-2">
	<?php 
	$sale_type=$rows->sale_type;
	if ($sale_type=='cr')
	
	{

echo "Invoice";
	}
	else
	{


echo "Cash Sale";		
		
	}

?>

</td>
	<td align="center"><a href="generate_sales_returns.php?sales_id=<?php echo $rows->sales_id;?>">Record Sales Returns</a></td>

 <!--<td></td>-->
	
   
    </tr>

  <?php 
  
  }
  
  ?>
  
  </table>
  <table width="100%" border="0">
  <tr bgcolor="#FFFFCC">

  


     <td align="center" width="150"><strong></strong></td>   

    <td align="center" width="150"><strong></strong></td>
<td align="center" width="300"><strong></strong></td>  


  <td align="right" width="150"><strong><font size="+1" color="#ff0000"><?php echo number_format($job_card_ttl,2); ?></font></strong></td>
  <td align="right" width="150"><strong><font size="+1" color="#ff0000"><?php echo number_format($grnd_inv_payment,2); ?></font></strong></td>
  <td align="right" width="150"><strong><font size="+1" color="#ff0000"><?php echo number_format($gnd_bal,2); ?></font></strong></td>

	<td align="center" width="150"><strong></strong></td>    
	<td align="center" width="150"><strong></strong></td>    
	<td align="center" width="150"><strong></strong></td>   
    <td align="center" width="150"><strong></strong></td>

  
  </tr>
  <?php
  
  }
  
  else 
  
  {
  ?>
  
  <tr bgcolor="#FFFFCC" height="30"><td colspan="11" align="center"><font color="#ff0000"><strong>No Results found!!</strong></font></td></tr>
  
  <?php 
  
  
  }
  
  
  ?>
  
  </table>
   </td></tr>	 
  
  
  
  
  
  
</table>
</form>
 
 <?php }?>